### ISSUE TITLE
Latest is broken

### ISSUE THREAD

**Issue by Jake-Shadle** [frewsxcv/rust-crates-index#121]
https://github.com/frewsxcv/rust-crates-index/commit/9ba7cac94ee6563ef2819d6112bf6eef81366f66 broke this crate if the `sparse-http` feature is enabled due to `read_cache_version` being removed, and it also made `get_index_details` crate private, the whole point of exposing it publicly was so that crates could use it to avoid duplicating logic this crate already performs if they want to have a custom CARGO_HOME directory without messing with the environment, but keep the canonical cargo directory structure.

**Comment by Logarithmus** [comment]
@kornelski kind ping

**Comment by kornelski** [comment]
Sorry to throw a wrench in your plans. A standalone `get_index_details` function that returned a tuple did not seem like it meant to be a proper public API. I'm aiming to publish 1.0 of this crate soon-ish, so I'd rather minimize the public API.

Can you explain use-cases for these functions?

For example, I wonder why you need `read_cache_version`. It seems like a low-level detail. There's `make_cache_request`/`parse_cache_response` that handle the cache version internally. Is that not sufficient? Maybe these functions should also return a lookup key, if you're storing the responses in some custom database?

I assume `get_index_details` is for deciding whether to instantiate sparse or git index?

**Comment by Jake-Shadle** [comment]
A request to a remote sparse HTTP index should have the local cache entries revision, so that the server can return a 304 if the local version is up to date with the latest in the index, if that version is not sent then the server will always respond with the full index entry every request.

The `get_index_details` was so that this crate consolidated some code, and made public so that external users could take advantage of not duplicating cargo's local index layout logic.

But if that doesn't fit with this crate's goals for 1.0 that's fine.

**Comment by kornelski** [comment]
But for making requests there's `make_cache_request`, so why do you need to set these cache validation headers yourself? Is `make_cache_request` not sufficient? I wonder if it should return a `RequestBuilder` instead of a `Request`.

I understand you wanted to consolidate code, but what do you use `get_index_details` for? Do you need it because you access the index directly? If so, what's missing in crates-index that you need direct access? 
The [Index::path](https://docs.rs/crates-index/latest/crates_index/struct.Index.html#method.path) exists. Why do you need the path from another method?

**Comment by Jake-Shadle** [comment]
> For making requests there's make_cache_request, so why do you need to set these cache validation headers yourself? Is make_cache_request not sufficient? I wonder if it should return a RequestBuilder instead of a Request.

I don't, that's the point of having `make_cache_request`, but since `read_cache_version` was completely removed, it broke compilation broken because [it's still being called](https://github.com/frewsxcv/rust-crates-index/blob/f0f45b76ce9a5410486adf57326bf761350a0e04/src/sparse_index.rs#L127). It's fine if you don't want it to be public, but there still needs to be a way to get the local revision of the cache entry so that the response can be minimal if it's up to date.

> I understand you wanted to consolidate code, but what do you use get_index_details for? Do you need it because you access the index directly? If so, what's missing in crates-index that you need direct access?
The [Index::path](https://docs.rs/crates-index/latest/crates_index/struct.Index.html#method.path) exists. Why do you need the path from another method?

Looking through the issues and previous PRs you seem very hesitant about breaking changes, so exposing `get_index_details` publicly seemed the easiest way to align `Index` and `SparseIndex`. I added `SparseIndex::with_path` and made it so that you specify the root path, rather than absolute path like `Index::with_path`, and beneath that path is the canonical cargo layout, with `SparseIndex::at_path` being semantically the same as `Index::with_path`. Making `get_index_details` public means that a user who wants the same behavior for `Index` can get the absolute path via that function before calling `Index::with_path`. If you don't want that behavior then I think `SparseIndex::with_path` should be replaced with the `SparseIndex::at_path` implementation (+the url check) so that the APIs are more similar. It's unfortunate if the user wants a canonical layout and this crate doesn't expose that publicly, but that's easy logic to write yourself by just copying what this crate or cargo does.

**Comment by kornelski** [comment]
> compilation broken because it's still being called

Ahh! I was mislead by the compiler warning that this function is unused (because the feature was default off). I've fixed this, and made sure it's tested.

**Comment by Jake-Shadle** [comment]
Fixed in ff8bebe
