### ISSUE TITLE
sparse-http test failing localy

### ISSUE THREAD

**Issue by ToBinio** [frewsxcv/rust-crates-index#126]
I am running into a minor problem with the sparse-http tests.

## Problem

The URI to String conversions is locally(Windows) a bit off. It creates Uri like this: `https://index.crates.io/se\rd\serde` in practice this isn't a problem because most if not all client can handle such problems but the test don't.

https://github.com/frewsxcv/rust-crates-index/blob/e0157d00a2fd4cc7652be81f9529b553314c8463/src/sparse_index.rs#L324

so the test always fails with:

```
thread 'sparse_index::http_tests::generates_request_for_local_cache_entry' panicked at 'assertion failed: `(left == right)`
  left: `https://index.crates.io/au\to\autocfg`,
 right: `"https://index.crates.io/au/to/autocfg"`', src\sparse_index.rs:332:9
```

## Solution

The question now is if this should be fixed and if so how.

- we could change it in the test by converting all `\` to `/`
- or we could fix it here where it seems like the `std::path::MAIN_SEPARATOR` is wrong on Windows
  https://github.com/frewsxcv/rust-crates-index/blob/e0157d00a2fd4cc7652be81f9529b553314c8463/src/lib.rs#L333

**Comment by Byron** [comment]
Could you retry this with the latest version?
It's probably still an issue though, and if you have a fix I'd be happy merge a PR. At that time I would take the liberty to also add windows CI runners to prevent regressions.
