### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by kornelski** [frewsxcv/rust-crates-index#132]
Due to very unpleasant and irreconcilable interactions with members of the rust community, including rust-lang org members on another project, I'm no longer interested in contributing to the rust ecosystem, and I'm resigning as a maintainer.

I don't have admin rights here, so please ask @frewsxcv for access.

**Comment by frewsxcv** [comment]
Thanks for all that you've done! Handed off permissions to @Byron.
