### ISSUE TITLE
Finding a new maintainer

### ISSUE THREAD

**Issue by ToBinio** [frewsxcv/rust-crates-index#134]
After the sad resignation of Kornelski in #132 (Kornelski thanks for all the great work ❤️) I believe it is vital to find a new maintainer as quickly as possible.

unfortunately, #132 got locked, so I am creating this issue.

there is already one application: https://github.com/frewsxcv/rust-crates-index/pull/129#issuecomment-1646785353
in my opinion, @Byron would be a good fit as he has already proven his skills and dedication with `gitoxide`

@frewsxcv please let us know how you would like to go forward

note:
sry, for being a bit annoying & unpatented but I just fair that this crate could get lost forever

**Comment by frewsxcv** [comment]
https://github.com/frewsxcv/rust-crates-index/pull/129#issuecomment-1655792025
