### ISSUE TITLE
Don't need to check out the repo to find crates

### ISSUE THREAD

**Issue by Eh2406** [frewsxcv/rust-crates-index#17]
Cargo has an optimisation [it does not check out the index,](https://github.com/rust-lang/cargo/pull/4026) it just does a fetch and then looks at the history. It would be nice to make the same change hear.

**Comment by kornelski** [comment]
I've looked into implementing it within existing interface, but it's not easy:

* current interface exposes filesystem paths

* git2 has built-in `.walk` that isn't compatible with iterators. Iterator over git trees is doable, but requires unsafe lifetime acrobatics (makes iterator struct self-referential).

* currently `crate_index_paths()` + `Crate::new` can be used with `rayon` to parallelize parsing. With git it'd be inefficient slow if every call opened the repo to get blob at path. `crates-index` could either expose opaque types wrapping blobs to make the same pattern work with something like `Crate::new_from_blob`, or it'd have to parallelize internally (e.g. use a channel for iteration).

**Comment by pksunkara** [comment]
@frewsxcv We actually encountered an issue because this isn't implemented. We were using this library to update the index such that our next cargo command wouldn't fail. But since `cargo` reads `origin/master` directly and since `origin` is not available anymore, this library does not update the index according to `cargo` and updates only the `master`

**Comment by frewsxcv** [comment]
If anyone wants to work on this, I'll happily add you as a contributor to the repo, just let me know.

**Comment by jyn514** [comment]
This would also be useful for docs.rs (cc @nemo157): https://github.com/rust-lang/docs.rs/pull/898/files#diff-61897eb13df1f5d907265cc866e45fdeR65-R67
