### ISSUE TITLE
API error resiliency

### ISSUE THREAD

**Issue by theduke** [frewsxcv/rust-crates-index#24]
Useful crate!

I just have one issue: the implementation uses a whole lot of `.unwrap()`.
It's unlikely for failures to occur but very much possible, mostly with IO errors (think directory moved, disk inaccessible, ...) which can become an issue in a long running application.

It would be great to have `Crates` be `Iterator<Item = Result<Crate, Error>>` instead.

**Comment by kornelski** [comment]
There's `Crate::new_checked()` now. You can iterate over crates yourself. I use this:

```rust
let indexed_crates: HashMap<_,_> = crates_io_index.crate_index_paths().par_bridge()
                .filter_map(|path| {
                    let c = crates_index::Crate::new_checked(path).ok()?;
                    Some((c.name().to_ascii_lowercase(), c))
                })
                .collect();

```
