### ISSUE TITLE
Expose Crate::from_slice

### ISSUE THREAD

**Issue by jyn514** [frewsxcv/rust-crates-index#38]
Right now the only public method to construct a crate is [`Crate::new`](https://docs.rs/crates-index/0.15.0/src/crates_index/lib.rs.html#365), which requires a filename. However if the file is stored in a git compressed packfile, it may not have its own filename (see https://github.com/rust-lang/docs.rs/pull/898#discussion_r461501149). Since `Crate::new` trivially calls `Crate::from_slice` after, is it possible to expose that as a public method?

cc @nemo157

**Comment by kornelski** [comment]
Done
