### ISSUE TITLE
Building without OpenSSL

### ISSUE THREAD

**Issue by UebelAndre** [frewsxcv/rust-crates-index#64]
Is it possible to build this crate without any requirement on openssl? I'm looking for something that can parse a local crates index and has no need to access the network. Is this currently possible or if not is that something that would make sense to support?

**Comment by kornelski** [comment]
This crate doesn't depend on openssl directly. It depends on git2 -> libgit2-sys -> git transports.

So in theory it could be possible to disable remote git transports.

**Comment by UebelAndre** [comment]
Yeah, looking at [git2/Cargo.toml](https://github.com/rust-lang/git2-rs/blob/94b6240106210f1804dd8e272e0a4c1349d31c81/Cargo.toml) and [ligit2-sys](https://github.com/rust-lang/git2-rs/blob/94b6240106210f1804dd8e272e0a4c1349d31c81/libgit2-sys/Cargo.toml), the `OpenSSL` dependencies all seem optional and as though this crate could be updated to move that into a feature of some sorts as well. Or is there something I'm not understanding about features or the dependency graph?

**Comment by kornelski** [comment]
You're correct. It can be done with feature flags.
