### ISSUE TITLE
git auth/config is not respected

### ISSUE THREAD

**Issue by ordian** [frewsxcv/rust-crates-index#65]
See https://github.com/rust-lang/cargo/pull/5914 for the reference.

This causes https://github.com/killercup/cargo-edit/issues/515.

**Comment by kornelski** [comment]
This is a problem of the git2 crate: https://github.com/rust-lang/git2-rs/issues/600

**Comment by epage** [comment]
Looks like `cargo` handles that in src/cargo/sources/git/utils.rs in `with_authentication`

**Comment by epage** [comment]
Please re-open this.
- Looking at the linked issue, that issue is not any specific crate's fault but a question of where the logic should live
- Regardless of the implementation details, this is impacting end-users of this crate and and is a defect against this crate.

**Comment by kornelski** [comment]
It's also a dupe of #37

**Comment by epage** [comment]
Since this was closed, I split out the config part as https://github.com/frewsxcv/rust-crates-index/issues/66
