### ISSUE TITLE
Index duplicate entries with conflicting checksum

### ISSUE THREAD

**Issue by pinkforest** [frewsxcv/rust-crates-index#73]
### Issue

Related to: 

https://github.com/rust-lang/crates.io/issues/4418

crates.io-index seems to serve duplicate index with conflicting checksums for some reason -

Looking at the index for the wright crate from:

https://github.com/rust-lang/crates.io-index/blob/master/wr/ig/wright

Version 0.2.2 for some reason has a confilicting checksum
```json
{"name":"wright","vers":"0.2.2","deps":[{"name":"ansi_term","req":"^0.10.2","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"regex","req":"^0.2","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"}],"cksum":"8261a34961de4a333d2c8e15309c32d35df864709799112002edcffc1316369f","features":{},"yanked":false}
{"name":"wright","vers":"0.2.2","deps":[{"name":"ansi_term","req":"^0.10.2","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"},{"name":"regex","req":"^0.2","features":[],"optional":false,"default_features":true,"target":null,"kind":"normal"}],"cksum":"14f813076f3bd61b143e7094808057970f40366ee27b1252b758b407fbc661d2","features":{},"yanked":false}
```

The checksum that is served by static.crates.io is the second entry
`14f813076f3bd61b143e7094808057970f40366ee27b1252b758b407fbc661d2`

crates-index crate Index API also works in a way that you have to iterate all versions and that iterator also returns the two duplicates instead of failing - I think it should fail in this case.

crates-index Index iterates over both entries and the applications can often use only the first entry - with incorrect checksum

This can cause applications using crates-index to fail when the downloaded actual .crate had checksum from second entry that wasn't picked up first.

Applications that upon iteration would override checksum on second entry would work whilst the ones that pick the first to compare would fail in this case.

I've never seen anyone actually checking the seemingly possible case that Index gives duplicates such as this - conflicting checksums for a same version.

### Expected Behavior

crates-index Index should return an error if there
- [ ] are multiple duplicate versions of same version especially ones which may have conflicting checksum

**Comment by pinkforest** [comment]
I went thru the ecosystem and found

 - [] - zaif-api   - 0.1.0   - duplicates 1 conflicts 0
 - [] - yarte_config   - 0.3.1   - duplicates 1 conflicts 0
 - [] - wright   - 0.2.2   - duplicates 1 conflicts 1
 - [] - tentacle   - 0.2.1   - duplicates 1 conflicts 0
 - [] - stitch   - 0.1.0   - duplicates 1 conflicts 1
 - [] - stund   - 0.1.6   - duplicates 1 conflicts 0
 - [] - sample_planning   - 0.0.3   - duplicates 1 conflicts 0
 - [] - replicante_agent_models   - 0.1.1   - duplicates 1 conflicts 0
 - [] - rahashmap   - 0.2.14   - duplicates 1 conflicts 0
 - [] - prettyprint   - 0.6.0   - duplicates 1 conflicts 0
 - [] - miracl_amcl   - 3.2.1   - duplicates 1 conflicts 0
 - [] - lelet   - 1.2.9   - duplicates 1 conflicts 0
 - [] - g2gen   - 0.2.1   - duplicates 1 conflicts 0
 - [] - fluence   - 0.0.12   - duplicates 1 conflicts 0
 - [] - ext-php-rs-derive   - 0.0.7   - duplicates 1 conflicts 0
 - [] - embly   - 0.0.2   - duplicates 1 conflicts 0
 - [] - dynomite   - 0.4.1   - duplicates 1 conflicts 0
 - [] - dep_c   - 1.0.0   - duplicates 1 conflicts 0
 - [] - dep_d   - 3.1.0   - duplicates 1 conflicts 0
 - [] - crossbeam_requests   - 0.2.0   - duplicates 1 conflicts 0
 - [] - clickhouse-rs   - 0.1.14   - duplicates 1 conflicts 0
 - [] - clipars   - 1.1.2   - duplicates 1 conflicts 0
 - [] - canparse   - 0.1.4   - duplicates 1 conflicts 0
 - [] - base64-stream   - 1.2.2   - duplicates 1 conflicts 0
 - [] - async-stdio   - 0.3.0-alpha.1   - duplicates 1 conflicts 0
 - [] - ccl   - 0.5.1   - duplicates 1 conflicts 0
 - [] - kit   - 0.0.1   - duplicates 1 conflicts 0
 - [] - sml   - 0.1.16   - duplicates 1 conflicts 0

Total crates with duplicates: 28, checksum conflicts: 2

Wonderful edge case isn't it...

**Comment by kornelski** [comment]
It is concerning that such data corruption happened. It's an indication of a bug or maybe even a security issue with crates.io.

I don't think there's any point in changing crates-index create to work around this. crates.io needs to track down how this happened, and fix their registry data.

**Comment by pinkforest** [comment]
Typically applications/libraries which handle data are supposed or expected to validate the data they provide downstream when it is possible to do so.

Granted crates.io entries are in a form that implies array style entry instead of key-by-version uniqueness -

Unless I am mistaken -

Was there any particular reason API designed so that you have to iterate every version in order to find the version you are looking for just blindly following what the input data gives?

Was it done perhaps to just provide transparent representation of the data without any validation.

There would be a benefit to add a method for fetching particular version and if multiple version(s) are found this should be validated in this case if this type of interface is added -

If this isn't the case the guarantees should be documented - e.g. the following of data transparently without validating it.

**Comment by pinkforest** [comment]
@kornelski Are you happy if I submit a doc PR to clarify that crates-index does not impose any additional unique constraint on version from crates.io-index and follows the index as-is - which can close this one off?

I've cleaned up the red herrings off from the index now.

**Comment by kornelski** [comment]
Thanks for cleaning it up. Documentation updates are always welcome.

**Comment by pinkforest** [comment]
Cool I clarified a bit in #76
