### ISSUE TITLE
Support upcoming `feature` features in the index

### ISSUE THREAD

**Issue by epage** [frewsxcv/rust-crates-index#74]
https://rust-lang.github.io/rfcs/3143-cargo-weak-namespaced-features.html is planned for 1.60 and includes new fields in the index to get the extended `feature` information.

**Comment by kornelski** [comment]
As far as I can tell, there's nothing new in terms of the data structure. It's a microsyntax within field values.

I don't know if I should be building an abstraction layer on top of that.

**Comment by epage** [comment]
Maybe I missed it but I didn't see support for the [features2 field](https://rust-lang.github.io/rfcs/3143-cargo-weak-namespaced-features.html#index-changes).  If you already support that, then that works.

**Comment by kornelski** [comment]
Oh I see. I've been looking at user deocs.
