### ISSUE TITLE
Replace git2 with gitoxide

### ISSUE THREAD

**Issue by passcod** [frewsxcv/rust-crates-index#82]
Crates using this (e.g. binstall) keep getting libgit2 linking errors when one updates and the other doesn't. Gitoxide is a pretty good replacement that by nature will never have this issue.

There's also other git2 related issues, but I don't know off-hand if they'd be helped by this.

Is this project interested in this? To be clear, this is a proposal to contribute this myself.

**Comment by kornelski** [comment]
Yes, it would be great to have it as an option.

**Comment by somehowchris** [comment]
BTW, https://github.com/Byron/gitoxide/projects/1#card-66770647

**Comment by Shnatsel** [comment]
I'm interested in seeing this happen for `cargo audit` in order to remove the dependency on OpenSSL. `libgit2` has a hard dependency on OpenSSL, and projects that expose its API backed by `rustls` (MesaLink, TabbySSL) appear to be dead.

**Comment by Byron** [comment]
I have turned the previously linked card into [a tracking ticket](https://github.com/Byron/gitoxide/issues/574) with some analysis on the features that `gitoxide` would need to support, probably without being complete as the analysis was made some time ago.

My guess is that `gitoxide` can support the needs of `crates-index` already.

**Comment by Jake-Shadle** [comment]
FYI here is an [implementation](https://github.com/EmbarkStudios/tame-index/blob/a42c510f73760fd9893d67cd9e8d2960de71c5bb/src/index/git_remote.rs) for providing clone/fetch/blob reading for a git registry index that can be used as an inspiration for getting started on a PR to close this issue.

**Comment by Byron** [comment]
Thanks so much for sharing! I think particularly interesting could be [how to get a crate from a cloned index](https://github.com/EmbarkStudios/tame-index/blob/a42c510f73760fd9893d67cd9e8d2960de71c5bb/src/index/git_remote.rs#L90-L126). For the actual cloning/fetching, there might also be simpler ways [as done in `crates-index-diff`](https://github.com/Byron/crates-index-diff-rs/blob/main/src/index/init.rs#L57) for instance.

With that said, it's nice to see that the fetch API is powerful enough to support any case, even though I hope that over time, the common cases can be supported with tailored and neat APIs for clarity. With that said, I hope that if there is anything you would like to see improved, you will let me know :), @Jake-Shadle .

**Comment by Jake-Shadle** [comment]
There were definitely some issues figuring out how it works, was planning on opening some issues on your repo later.
