### ISSUE TITLE
Sparse registry support

### ISSUE THREAD

**Issue by Shnatsel** [frewsxcv/rust-crates-index#87]
Cargo is currently testing a sparse registry served over HTTPS, instead of downloading the entire git repo: https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html

Are there any plans to support it in this crate?

I'm looking to use it in [`cargo audit`](https://crates.io/crates/cargo-audit) for two reasons:

1. Shorter CI times without having to download the entire registry
2. Removing the dependency on OpenSSL via `libgit2` and replacing it with `rustls`. (Although #82 would also solve this)

**Comment by Byron** [comment]
> Shorter CI times without having to download the entire registry

Note that I am actively working on supporting shallow clones in `cargo` by the end of the year, and with it being available in `gitoxide` it should be possible to support it here as well.

In case using `gitoxide` here is an option for the maintainers, here is [my tracking ticket](https://github.com/Byron/gitoxide/issues/574) with some analysis on the required features that `gitoxide` would need to support, probably without being complete as the analysis was made some time ago.

**Comment by Shnatsel** [comment]
I understand that the [Cargo sparse registry](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#sparse-registry) is distinct from Git sparse checkouts, and doesn't use Git at all - just plain HTTP. Am I mistaken?

**Comment by Byron** [comment]
No, you are not mistaken and maybe my comment is out of place or confusing. 

I was referring to the shorter CI times specifically and that these will also be reduced once shallow clones are supported by `gitoxide`. My feeling is that `gitoxide` will land here before sparse-index support is ready to be used outside of `cargo`, unless the Cargo Team is making sure the sparse registry is accessible via some API crate which may well be the case.

**Comment by kornelski** [comment]
Yes, I think this crate could support a sparse registry. You could DIY a solution already, because for fetching a single crate that's a matter of making an HTTP request, and this crate exposes `Crate::parse_from_slice` already.
