### ISSUE TITLE
getting INDEX_GIT_URL

### ISSUE THREAD

**Issue by dalance** [frewsxcv/rust-crates-index#95]
Is there any way to get `INDEX_GIT_URL`?

My application ( [cargo-trend](https://github.com/dalance/cargo-trend) ) goes back through git history to gather history information, so I don't want to share the index with cargo.
Therefore, I'm tring to replace `Index::new` to `Index::with_path`, but I can't get `INDEX_GIT_URL` which is used in `Index::new`.

**Comment by kornelski** [comment]
I've made it public.
